<?php
$v_params = $this->getParams();
$v_params['body_css'] = 'lock';

include "views/layout/header.phtml";
?>
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
    <div class="lockscreen-logo">
        <a href="#"><b>Sismissing</b></a>
    </div>
    <!-- User name -->
    <div class="lockscreen-name"><?php echo $_SESSION['st_name'];?></div>

    <!-- START LOCK SCREEN ITEM -->
    <div class="lockscreen-item">
        <!-- lockscreen image -->
        <div class="lockscreen-image">
            <img src="/Sismissing/assets/img/user1.png" alt="User Image">
        </div>
        <!-- /.lockscreen-image -->

        <!-- lockscreen credentials (contains the form) -->
        <form class="lockscreen-credentials" method="POST">
            <div class="input-group">
                <input type="password" id="st_password" name="st_password" class="form-control" placeholder="password">
                <div class="input-group-append">
                    <button type="submit" class="btn">
                        <i class="fas fa-arrow-right text-muted"></i>
                    </button>
                </div>
            </div>
        </form>
        <!-- /.lockscreen credentials -->

    </div>
    <!-- /.lockscreen-item -->
    <div class="help-block text-center">
        Insira a sua senha para recuperar a sessão!
    </div>
    <div class="text-center">
        <a href="?ctrl=Login&act=logout">Ou entre com um novo usuário</a>
    </div>
</div>
<!-- /.center -->
<?php
include "views/layout/scriptjs.phtml";
?>
