<?php
require_once "models/UserModel.php";

$o_user = new UserModel();
$_COOKIE['st_name'] = $_SESSION['st_name'];
?>
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light" style="display: flex;">
    <!-- Left navbar links -->
    <ul class="navbar-nav ">
		 <!--li class="nav-item d-none d-sm-inline-block"-->
		 <li class="nav-item">
            <a href="?ctrl=Home&act=LandPage" class="nav-link" style="display: flex;">
                <img src="/Sismissing/assets/img/miss.jfif" style="">
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <span class="nav-link" style="color:#007E7A;font-weight: bold;">
                Sismissing - Sistema de informação de Desaparecidos &nbsp;-&nbsp; <span style="color:#ECB11F;"></span>
            </span>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
		 <!--li class="nav-item d-none d-sm-inline-block"-->
     <li class="nav-item">
       <img class="direct-chat-img" src="/Sismissing/assets/img/user1.png" alt="message user image">
     </li>
     <li class="nav-item">

			 <span class="nav-link" style="color: #ECB11F; font-size:13px; font-weight: normal;"><?php echo "".$_COOKIE["st_name"];?></span>
		</li>

        <!-- Logout Button -->
        <li class="nav-item">
            <a class="nav-link" href="<?php echo "/Sismissing/sair.php";?>" role="button">
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->
