<!-- jQuery -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/jquery/jquery.js"></script>
<!-- Bootstrap 4 -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/bootstrap/js/bootstrap.bundle.js"></script>
<!-- Select2 -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/select2/js/select2.js"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
<!-- InputMask -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/moment/moment.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/inputmask/jquery.inputmask.min.js"></script>
<!-- date-range-picker -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
<!-- bootstrap color picker -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Bootstrap Switch -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
<!-- BS-Stepper -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/bs-stepper/js/bs-stepper.min.js"></script>
<!-- dropzonejs -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/dropzone/min/dropzone.min.js"></script>
<!-- AdminLTE App -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/dist/js/adminlte.js"></script>
<!-- DataTables  & Plugins -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/jszip/jszip.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/pdfmake/pdfmake.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/pdfmake/vfs_fonts.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<!-- ChartJS -->
<script src="/Sismissing/vendor/almasaeed2010/adminlte/plugins/chart.js/Chart.min.js"></script>
<!-- Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</body>
</html>
